name: Markdown Chunk Generator
description: Generate chunks for the Siv3D documentation

inputs:
  siv3d-docs-path:
    description: The path to the siv3d.docs directory
    required: true
  siv3d-docs-language:
    description: The language of the siv3d.docs directory
    required: true
  siv3d-docs-version:
    description: The current commit hash of siv3d.docs repository
    required: true
  chunks-output-path:
    description: The path to the chunks.json file
  code-blocks-output-path:
    description: The path to the code-blocks.json file
  disable-validation:
    description: Skip data validation (true or false)
    default: 'false'

runs:
  using: node20
  main: dist/index.js
