name: Sync Documentation Chunks to Algolia

on:
  workflow_dispatch:
    inputs:
      siv3d_docs_commit_hash:
        description: 'siv3d.docs repository commit hash'
        required: true
        type: string

jobs:
  sync-algolia:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout chunk-generator repository
        uses: actions/checkout@v4
        
      - name: Checkout siv3d.docs repository
        uses: actions/checkout@v4
        with:
          repository: 'Siv3D/siv3d.docs'
          ref: ${{ github.event.inputs.siv3d_docs_commit_hash }}
          path: 'siv3d.docs'
          
      - name: Generate chunks for Japanese
        uses: ./chunk-generator/
        with:
          siv3d-docs-dir: ./siv3d.docs
          siv3d-docs-language: ja-jp
          siv3d-docs-version: ${{ github.event.inputs.siv3d_docs_commit_hash }}
          chunks-output-file: chunks-ja-jp.json
          code-blocks-output-dir: code-blocks-ja-jp
          
      - name: Generate chunks for English
        uses: ./chunk-generator/
        with:
          siv3d-docs-dir: ./siv3d.docs
          siv3d-docs-language: en-us
          siv3d-docs-version: ${{ github.event.inputs.siv3d_docs_commit_hash }}
          chunks-output-file: chunks-en-us.json
          code-blocks-output-dir: code-blocks-en-us
          
      - name: Upload generated chunks
        uses: actions/upload-artifact@v4
        with:
          name: generated-chunks
          path: |
            chunks-ja-jp.json
            code-blocks-ja-jp
            chunks-en-us.json
            code-blocks-en-us
      
      - name: Upload generated chunks to Algolia for Japanese
        uses: ./algolia-uploader/
        with:
          algolia-app-id: ${{ vars.ALGOLIA_APP_ID }}
          algolia-api-key: ${{ secrets.ALGOLIA_WRITE_OBJECT_API_KEY }}
          algolia-index-name: "siv3d-docs-jp"
          chunks-file-path: chunks-ja-jp.json
          siv3d-docs-version: ${{ github.event.inputs.siv3d_docs_commit_hash }}
          
      - name: Upload generated chunks to Algolia for English
        uses: ./algolia-uploader/
        with:
          algolia-app-id: ${{ vars.ALGOLIA_APP_ID }}
          algolia-api-key: ${{ secrets.ALGOLIA_WRITE_OBJECT_API_KEY }}
          algolia-index-name: "siv3d-docs-en"
          chunks-file-path: chunks-en-us.json
          siv3d-docs-version: ${{ github.event.inputs.siv3d_docs_commit_hash }}
